import wx

class ToDoItem(wx.Panel):
    def __init__(self, parent, task, priority, on_delete):
        super().__init__(parent)
        self.task = task
        self.priority = priority
        self.on_delete = on_delete

        self.checkbox = wx.CheckBox(self, label=task)
        self.priority_label = wx.StaticText(self, label=self.get_priority_text(priority))

        self.checkbox.Bind(wx.EVT_CHECKBOX, self.on_checkbox_checked)

        sizer = wx.BoxSizer(wx.HORIZONTAL)
        sizer.Add(self.checkbox, 0, wx.ALL, 5)
        sizer.Add(self.priority_label, 0, wx.ALL, 5)

        self.SetSizer(sizer)
        self.Layout()

    def get_priority_text(self, priority):
        if priority == 0:
            return "High Priority"
        elif priority == 1:
            return "Medium Priority"
        else:
            return "Low Priority"

    def on_checkbox_checked(self, event):
        if self.checkbox.GetValue():
            wx.CallAfter(self.on_delete, self)  # Delayed destruction

class ToDoListFrame(wx.Frame):
    def __init__(self):
        super().__init__(None, title="To-Do List", size=(600, 400))
        self.panel = wx.Panel(self)

        # this segment of code (lines 40-57) creating all the widgets used in the UI application of this 
        # project were generated by AI
        self.task_text_ctrl = wx.TextCtrl(self.panel, style=wx.TE_PROCESS_ENTER)
        self.priority_choice = wx.Choice(self.panel, choices=["High Priority", "Medium Priority", "Low Priority"])
        self.priority_choice.SetSelection(0)
        self.add_button = wx.Button(self.panel, label="Add Task")
        self.add_button.Bind(wx.EVT_BUTTON, self.on_add_task) # run on_add_task() function when user clicks button

        input_sizer = wx.BoxSizer(wx.HORIZONTAL)
        input_sizer.Add(self.task_text_ctrl, 1, wx.ALL | wx.EXPAND, 5)
        input_sizer.Add(self.priority_choice, 0, wx.ALL | wx.EXPAND, 5)
        input_sizer.Add(self.add_button, 0, wx.ALL | wx.EXPAND, 5)

        self.tasks_sizer = wx.BoxSizer(wx.VERTICAL)

        main_sizer = wx.BoxSizer(wx.VERTICAL)
        main_sizer.Add(input_sizer, 0, wx.EXPAND|wx.ALL, 10)
        main_sizer.Add(self.tasks_sizer, 1, wx.EXPAND|wx.ALL, 10)

        self.panel.SetSizer(main_sizer)

    def on_add_task(self, event): # adds a task to the list
        task = self.task_text_ctrl.GetValue() # get user input from the textbox
        priority = self.priority_choice.GetSelection() # read user choice from priority choices
        if task: 
            todo_item = ToDoItem(self.panel, task, priority, self.on_delete_task)
            if priority == 0: 
                self.tasks_sizer.Insert(0, todo_item, 0, wx.ALL | wx.EXPAND, 5)
            else:
                self.tasks_sizer.Add(todo_item, 0, wx.ALL | wx.EXPAND, 5)
            self.panel.Layout()
            self.task_text_ctrl.SetValue("")

    def on_delete_task(self, task_item):
        task_item.Destroy()
        self.panel.Layout()

if __name__ == "__main__":
    app = wx.App(False)
    frame = ToDoListFrame()
    frame.Show(True)
    app.MainLoop()
